//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sneakerShopEntities2 : DbContext
    {
        public sneakerShopEntities2()
            : base("name=sneakerShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartItem> CartItem { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<imagesProduct> imagesProduct { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<paymentType> paymentType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Shipment> Shipment { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
