//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailId { get; set; }
        public int orderID { get; set; }
        public Nullable<int> stockID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> unitPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
